OpenCS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from OpenCS import views

from tastypie.api import Api
from glossary.api import register_to_api as register_glossary_api
from quiz.api import register_to_api as register_quiz_api
from exploration.api import register_to_api as register_exp_api
from slides.api import register_to_api as register_slides_api
from courseware.api import register_to_api as register_courseware_api
from snippets.api import SnippetResource

# Create the REST API
v1_api = Api(api_name="v1")
register_glossary_api(v1_api)
register_quiz_api(v1_api)
register_exp_api(v1_api)
register_slides_api(v1_api)
register_courseware_api(v1_api)
v1_api.register(SnippetResource())

# Change the admin site header and title
# TODO: decide on making a custom admin.site for this
admin.site.site_header = "OpenCS Administration"
admin.site.site_header = "OpenCS Site Admin"


urlpatterns = patterns('',
    # For the Final Site
    url(r'^api/', include(v1_api.urls)),
    url(r'^web-container/', include('webhost.urls'), name='webcontainer'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^python-from-scratch/python-panel/', views.pypanel, name='pypanel'),
    url(r'^glossary/', include('glossary.urls', namespace='glossary')),
)

# XXX The flatpages have priority over courseware
urlpatterns += patterns('django.contrib.flatpages.views',
    url(r'^/', include('django.contrib.flatpages.urls')),
)

urlpatterns += patterns('courseware.views',
    url(r'', include('courseware.urls', namespace="courseware")),
)

# For the Dev-mode media serving
from django.conf import settings
from django.conf.urls.static import static
if settings.DEVMODE:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glossary/urls.py
from django.conf.urls import patterns, url

from glossary import views

urlpatterns = patterns('', 
        url(r'^$', views.index, name='global'),
        url(r'^(?P<unit_number>\d+)/$', views.glossary, name='glossary'),
        url(r'^word/(?P<word_id>\d+)/$', views.word, name='word_detail'),
        )

quiz/urls.py
from django.conf.urls import patterns, url

from quiz import views

urlpatterns = patterns('', 
        url(r'^$', views.index, name='quiz/index'),
        url(r'^(?P<pk>\d+)/$', views.quiz, name='quiz/quiz'),
        )

glossary/models.py
from django.db import models

# Create your models here.
class Word(models.Model):
    """ An individual word/term

    The associated step and module numbers are saved, because they're available
    and might be needed in the future. These refer to the first appearance of the term.
    
    Attributes: 
        word (CharField):  The word or term for the glossary item
        definition (CharField): The definition of the term
        unit_number (PositiveSmallIntegerField): The unit number the word is first used in
        module_number (PositiveSmallIntegerField): The module number inside that unit
    """

    # Attributes
    word = models.CharField(max_length=200)  # TODO: more reasonable lengths?
    definition = models.CharField(max_length=200);

    # "Relations"
    unit_number = models.PositiveSmallIntegerField(default=0, verbose_name="Module Number")
    module_number = models.PositiveSmallIntegerField(default=0, verbose_name="Step Number")

    # Functions
    def copyFrom(self, w):
        """ Creates a copy of the word.
        """
        self.word = w.word
        self.definition = w.definition

    def is_same_as(self,w):
        """ Checks if a Word has the same term and definition as this one
        """
        return w.word == self.word and w.definition == self.definition

    def __str__(self):
        return self.word + " - " + self.definition

    class Meta:
        ordering = ['word']

class Glossary(models.Model):
    """ A collection of terms and definitions

    Attributes:
        word_set (ManyToManyField): The set of words in the dictionary
        unit_number (PositiveSmallIntegerField): The unit number this glossary is connected with
        title (CharField): The title of the glossary (displayed at the top of the page)
    """

    # Relations
    word_set = models.ManyToManyField(Word)

    # "Relations"
    unit_number = models.PositiveSmallIntegerField(default=0, verbose_name="Module Number")

    # Attributes
    title = models.CharField(max_length=200)

    # Functions
    def words(self):
        return self.word_set.order_by('word')

    def __str__(self):
        courses = self.course_set.all()
        if courses:
            return self.title + ' (' + ', '.join([ str(c) for c in courses ]) + ')'
        else:
            return self.title + ' (unassigned)'

    class Meta:
        ordering = ['unit_number']
        verbose_name_plural = "Glossaries"


# Now for basically the same thing, but for Built-Ins
class BuiltIn(models.Model):
    """ A description of a built-in function or constant

    The associated step and module numbers are saved, because they're available
    and might be needed in the future. These refer to the first appearance of the term.
    
    Attributes: 
        name (CharField):  The name/identifier of the builtin
        description (Text): The simple description
        explanation (Text): An explanation of the function
        language (Charfield): The language it is built into
        b_type (Charfield): The type of the built-in (e.g. element, function, property)

        module (Module): The module it first appears in
        example_set (BuiltInExamples): The set of examples for this builtin

    """

    # Attributes
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    explanation = models.TextField(blank=True)

    PYTHON = 'Python'
    HTML = 'HTML'
    CSS = 'CSS'
    JS = 'JS'
    LANGUAGE_CHOICES = (
            (PYTHON, 'Python'),
            (HTML, 'HTML'),
            (CSS, 'css'),
            (JS, 'javascript'),
            )
    language = models.CharField(max_length=6, choices=LANGUAGE_CHOICES, default=PYTHON)
    b_type = models.CharField(max_length=50, blank=True, verbose_name='Type')

    # Relations
    module = models.ForeignKey('courseware.Module', blank=True, null=True, on_delete=models.SET_NULL)

    # Functions
    def course(self):
        if self.module:
            return self.module.unit.course
        else:
            return None

    def unit_number(self):
        if self.module:
            return self.module.unit.position
        else:
            return None

    def module_number(self):
        if self.module:
            return self.module.position
        else:
            return None

    def example(self):
        exs = self.example_set.all()
        if exs:
            return exs[0].text
        else:
            return None

    def __str__(self):
        return self.name + ' ' + self.language

    class Meta:
        ordering = ['language', 'name']

class BuiltInExample(models.Model):
    """ An example for a built-in function

    Attributes:
        text (TextField): The actual example (in html)
        builtin (BuiltIn): The builtin function it is an example of
    """

    # Attributes
    text = models.TextField()

    # Relations
    builtin = models.ForeignKey(BuiltIn, related_name='example_set')

    # Functions
    def __str__(self):
        return self.builtin.name + '.example'

class BuiltInCollection(models.Model):
    """ A collection of builtin functions

    Attributes:
        builtin_set (ManyToManyField): The set of builtins in the collection
        title (CharField): The title of the collection (displayed at the top of the page)
    """

    # Relations
    builtin_set = models.ManyToManyField(BuiltIn, through='BuiltInRelation', through_fields=('collection', 'builtin'))

    # Attributes
    title = models.CharField(max_length=200)

    # Functions
    def builtins(self):
        """Retrieves the builtin_set in the correct order
        """
        return self.builtin_set.order_by('relation_set__order')

    def __str__(self):
        courses = self.course_set.all()
        if courses:
            return self.title + ' (' + ', '.join([ str(c) for c in courses ]) + ')'
        else:
            return self.title + ' (unassigned)'


    class Meta:
        verbose_name = "Built-in Collection"

class BuiltInRelation(models.Model):
    collection = models.ForeignKey(BuiltInCollection, related_name='relation_set')
    builtin = models.ForeignKey(BuiltIn, related_name='relation_set')
    order = models.PositiveSmallIntegerField(default=0)

glossary/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404

from glossary.models import Word, Glossary

def index(request):
    word_list = Word.objects.order_by('word')
    context = {'glossary': {'title': 'Glossary'}, 'word_list': word_list}
    return render(request, 'glossary/global.html', context)

def glossary(request, unit_number):
    glossaries = get_list_or_404(Glossary, unit_number=unit_number)
    return render(request, 'glossary/glossary.html', {'glossary_list': glossaries, 'unit': glossaries[0].title })

def word(request, word_id):
    w = get_object_or_404(Word, id=word_id)
    return render(request, 'glossary/word_details.html', {'word': w})

glossary/templates/glossary/global.html
{% extends "base.html" %}
{% block breadcrumb %}
{{ block.super }}
    &gt;<a href="">Glossary</a>
{% endblock breadcrumb %}
{% block content %}
<section id="main">
<h1>{{ glossary.title }}</h1>    

<ul>
{% for word in word_list %}
    <li><a href="{% url 'glossary:word_detail' word.id %}">{{ word.word }}</a> &ndash; {{ word.definition|safe }}</li>
{% endfor %}
</ul>
</section>
{% endblock content %}

glossary/templates/glossary/glossary.html
{% extends "base.html" %}

{% block breadcrumb %}
{{ block.super }}
<li>&gt;</li><li><a href="{% url "glossary:global" %}">Glossary</a></li>
    {% if unit %}
        <li>&gt;</li><li><a href="">{{ unit.title }}</a></li>
    {% endif %}
{% endblock breadcrumb %}

{% block content %}
<section id="main">
{% for glossary in glossary_list %}
<h1>{{ glossary.title }}</h1>    

<ul>
{% for word in glossary.word_set.all %}
    <li><a href="{% url 'glossary:word_detail' word.id %}">{{ word.word }}</a> &ndash; {{ word.definition }}</li>
{% endfor %}
</ul>
{% endfor %}
</section>
{% endblock content %}

glossary/templates/glossary/index.html
{% extends "base.html" %}
{% block content %}
<section id="main">
{% if glossary_list %}
    <ul>
    {% for gloss in glossary_list %}
        <li><a href="{% url 'glossary' gloss.id %}">{{ gloss.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No glossaries are available.</p>
{% endif %}
</section>
{% endblock content %}

glossary/templates/glossary/test.html
<!DOCTYPE html>

<html>
<head>
<title>Test of angular glossary</title>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular-resource.js"></script>
<link rel="stylesheet" href="/static/css/glossary-module.css">
</head>

<body ng-app="glossaryModule">
<h1>This is a test of glossary services</h1>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a <glossary-term id=4></glossary-term> galley of type and scrambled it to make a type
specimen book. It has survived not only five centuries, but also the leap into
electronic typesetting, <glossary-term id=1></glossary-term>remaining essentially unchanged. It was popularised in
the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
and more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum.
</p>
</body>
<script src="/static/scripts/glossary/glossary-module.js"></script>
</html>

glossary/templates/glossary/word_details.html
{% extends "base.html" %}
{% block content %}
<section id="main">
<h1>{{ word.word }}</h1>
<p>{{ word.definition }}</p>
</section>
{% endblock content %}