OpenCS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from OpenCS import views

from tastypie.api import Api
from glossary.api import register_to_api as register_glossary_api
from quiz.api import register_to_api as register_quiz_api
from exploration.api import register_to_api as register_exp_api
from slides.api import register_to_api as register_slides_api
from courseware.api import register_to_api as register_courseware_api
from snippets.api import SnippetResource

# Create the REST API
v1_api = Api(api_name="v1")
register_glossary_api(v1_api)
register_quiz_api(v1_api)
register_exp_api(v1_api)
register_slides_api(v1_api)
register_courseware_api(v1_api)
v1_api.register(SnippetResource())

# Change the admin site header and title
# TODO: decide on making a custom admin.site for this
admin.site.site_header = "OpenCS Administration"
admin.site.site_header = "OpenCS Site Admin"


urlpatterns = patterns('',
    # For the Final Site
    url(r'^api/', include(v1_api.urls)),
    url(r'^web-container/', include('webhost.urls'), name='webcontainer'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^python-from-scratch/python-panel/', views.pypanel, name='pypanel'),
    url(r'^glossary/', include('glossary.urls', namespace='glossary')),
)

# XXX The flatpages have priority over courseware
urlpatterns += patterns('django.contrib.flatpages.views',
    url(r'^/', include('django.contrib.flatpages.urls')),
)

urlpatterns += patterns('courseware.views',
    url(r'', include('courseware.urls', namespace="courseware")),
)

# For the Dev-mode media serving
from django.conf import settings
from django.conf.urls.static import static
if settings.DEVMODE:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courseware/urls.py
from django.conf.urls import patterns, url

from courseware import views

urlpatterns = patterns('', 
        url(r'^$', views.index, name='index'),
        url(r'^(?P<course_slug>[-_\w]+)/$', views.course, name='course'),
        url(r'^(?P<course_slug>[-_\w]+)/(?P<unit_number>\d+)/$', views.unit, name='unit'),
        url(r'^(?P<course_slug>[-_\w]+)/(?P<unit_number>\d+)/(?P<module_number>\d+)/$', views.module, name='module'),
        url(r'^(?P<course_slug>[-_\w]+)/(?P<unit_number>\d+)/(?P<module_number>\d+)/transcript$', views.transcript, name='transcript'),
        url(r'^(?P<course_slug>[-_\w]+)/glossary/$', views.glossary, name='glossary'),
        url(r'^(?P<course_slug>[-_\w]+)/built-ins/$', views.builtins, name='builtins'),
        url(r'^(?P<course_slug>[-_\w]+)/videos/$', views.video_index, name='videos'),
        )

exploration/urls.py
from django.conf.urls import patterns, url

from exploration import views

urlpatterns = patterns('', 
        url(r'^$', views.index, name='exploration/index'),
        url(r'^(?P<pk>\d+)/$', views.exploration, name='exploration/exploration'),
        )

glossary/urls.py
from django.conf.urls import patterns, url

from glossary import views

urlpatterns = patterns('', 
        url(r'^$', views.index, name='global'),
        url(r'^(?P<unit_number>\d+)/$', views.glossary, name='glossary'),
        url(r'^word/(?P<word_id>\d+)/$', views.word, name='word_detail'),
        )

quiz/urls.py
from django.conf.urls import patterns, url

from quiz import views

urlpatterns = patterns('', 
        url(r'^$', views.index, name='quiz/index'),
        url(r'^(?P<pk>\d+)/$', views.quiz, name='quiz/quiz'),
        )

exploration/models.py
from django.db import models

from django.contrib.contenttypes.fields import GenericRelation
from courseware.models import Module

# Use json to serialize the lists of things for tests
import json
import re
import ast

# XXX We need a list of hints, so here's a list field
# taken from http://stackoverflow.com/questions/5216162/how-to-create-list-field-in-django
class ListField(models.TextField, metaclass=models.SubfieldBase):

    """ A Python list field

    The data is serialized as a string, then evaluated with ast
    """

    __metaclass__ = models.SubfieldBase
    description = "Stores a python list"

    def __init__(self, *args, **kwargs):
        super(ListField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        if not value:
            value = []

        if isinstance(value, list):
            return value

        converted =  ast.literal_eval(value)
        if not isinstance(converted, list):
            raise ValueError('value "%s" is not a list\n Original is %s' % (converted, repr(value)))
        return converted

    def get_prep_value(self, value):
        if value is None:
            return value

        return str(value)

    def value_to_string(self, obj):
        value = self._get_val_from_obj(obj)
        return self.get_db_prep_value(value)



class Exploration(models.Model):

    """A full multi-part code exploration

    There will be support for more languages in the future

    Attributes:
        language (CharField): one of ``["python",]``
        title (CharField): short title of the exploration (deprecated)
    """

    PYTHON = 'python'
    WEB = 'web'
    LANGUAGE_CHOICES = (
            (PYTHON, 'Python'),
            (WEB, 'Web Material'),
            )

    # Relations
    modules = GenericRelation(Module)

    # Attributes
    title = models.CharField(max_length=50)
    language = models.CharField(max_length=6, choices=LANGUAGE_CHOICES, default=PYTHON)

    # Functions
    def __str__(self):
        return str(self.title)

class Slide(models.Model):

    """One of the slides in an exploration
    
    Attributes:
        text (TextField): The slide's text contents
        post_text (TextField): The text to be added to the slide after running the code (presented as "notes)
        hints (ListField): A list of hints associated with the exercise
        allow_exception (BooleanField): If ``True``, the exercise is correct even with an exception. 
        left_pane_size (PositiveSmallIntegerField): relative size of the left pane, where ``6`` is 50%
        show_rendered (BooleanField): Whether the rendered pane should be shown
        show_console (BooleanField): Whether the console pane should be shown

        code (TextField): Default code for this slide
        replace_code (CharField): One of ``['n', 'r', 'p', 'a']`` for none, replace, prepend, append

    .e deprecated:: 0.3.0
        The ``code`` and ``replace_code`` attributes are deprecated. Use :class:`CodeBlock` instead.
    """

    NONE = 'n'
    REPLACE = 'r'
    PREPEND = 'p'
    APPEND = 'a'
    REPLACE_CHOICES = (
            (NONE,      'do nothing'),
            (REPLACE,   'replace code'),
            (PREPEND,   'prepend to code'),
            (APPEND,    'append to code'),
            )

    # Relations
    exploration = models.ForeignKey(Exploration)
    index = models.SmallIntegerField() # What order the slide is in in the exploration

    # Attributes
    text = models.TextField()
    post_text = models.TextField(blank=True)
    hints = ListField(default=[], blank=True)
    allow_exception = models.BooleanField(default=False)
    left_pane_size = models.PositiveSmallIntegerField(default=6)

    # These are going to be needed for the web course
    show_rendered = models.BooleanField(default=True)
    show_console = models.BooleanField(default=True)

    # XXX The following fields are to be deprecated in favour of ``CodeSample`` objects
    code = models.TextField(blank=True)
    replace_code = models.CharField(max_length=1, choices=REPLACE_CHOICES, default=NONE)
    
    # Functions
    def __str__(self):
        return "Slide " + str(self.index)
    
    _p_img = re.compile(r'(<img\s+alt="([^"]*)"\s+src=")([^"]*)')
    def save(self, *args, **kwargs):
        """
        Save the slide, first matching all the images to their source.

        The ``alt`` attribute for the ``<img>`` is matched against the ``SlideImage``'s ``title`` property
        """
        def _img_replace(match):
            "look up the src corresponding to the alt text"
            alt = match.group(2)
            src = self.image_set.filter(title=alt)
            if src:
                src = src[0].image.url
            else:
                src = ''
            return match.group(1) + src

        self.text = self._p_img.sub(_img_replace, self.text)
        self.post_text = self._p_img.sub(_img_replace, self.post_text)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['index']

# XXX I want this as a static method of ExplorationImage, but the name must be defined *before* the class definition
def _upload_path(instance, filename):
    """ Determine the path to upload an image to
    """
    return "images/exp-slides/%s/%s" % (instance.slide.exploration_id, filename)

class ExplorationImage(models.Model):

    """ An image to be included in a exploration slide

    Attributes:
        slide (Slide): The slide this image is used in
        title (CharField): The image title (to be matched with the ``alt`` attribute in the ``<img>`` tag)
        image (ImageField): The actual image
        width (IntegerField): width of the image
        height (IntegerField): height of the image
    """

    # Relations
    slide = models.ForeignKey(Slide, related_name='image_set')

    # Attributes
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to=_upload_path, 
                              height_field='height', width_field='width')
    width = models.IntegerField(editable=False)
    height = models.IntegerField(editable=False)

    # Functions
    def __str__(self):
        return self.title

class Test(models.Model):

    """ The test(s) associated with a slide

    Attributes:
        test_type (CharField): The type of test. One of ``['stdio', 'func', 'cont', 'ns']``
        input_values (TextField): Dependent on the ``test_type``:

            - list of input strings serialized in json for STDIO,
            - a function that tests the code for FUNCTION
            - list of necessary substrings serialized in json for CONTAINS
        output_values (TextField): Dependent on ``test_type``   

            - A list of strings for STDIO (paired with input_values), 
            - nothing for FUNCTION
            - list of illegal substrings for CONTAINS

        slide (ForeignKey): the slide the test is associated with
    """

    STDIO = 'stdio'
    FUNCTION = 'func'
    CONTAINS = 'cont'
    NUMSOL = 'ns'
    TEST_CHOICES = (
           (STDIO, 'standard in/out'),
            (FUNCTION, 'blackbox function'),
            (CONTAINS, 'code contents'),
            (NUMSOL, 'A numerical solution (in stdout)'),
            )

    # Relations
    slide = models.ForeignKey(Slide)

    # Attributes
    test_type = models.CharField(max_length=5, choices=TEST_CHOICES, default=STDIO)
    # XXX For now, we can let input/output values overload contains/notcontains
    input_values = models.TextField(default='[]')
    output_values = models.TextField(default='[]')

    # Controller functions
    def add_io(self, i, o):
        """ Add an stdio test case """
        if self.test_type == self.STDIO:
            iv = json.loads(self.input_values)
            ov = json.loads(self.output_values)
            iv.append(i)
            ov.append(o)
            self.input_values = json.dumps(iv)
            self.output_values = json.dumps(ov)
        else:
            raise Exception('Tried to set a test for the wrong test type')

    def add_contains(self, s):
        """ Add a 'contains' test case """
        if self.test_type == self.CONTAINS:
            iv = json.loads(self.input_values)
            iv.append(s)
            self.input_values = json.dumps(iv)
        else:
            raise Exception('Tried to set a test for the wrong test type')

    def add_omits(self, s):
        """ Add an 'omits' test case """
        if self.test_type == self.CONTAINS:
            ov = json.loads(self.output_values)
            ov.append(s)
            self.output_values = json.dumps(ov)
        else:
            raise Exception('Tried to set a test for the wrong test type')

    def set_numsol(self, s):
        """ Set the value for a numerical solution test"""
        if self.test_type == self.NUMSOL:
            self.output_values = s
        else:
            raise Exception('Tried to set a test for the wrong test type')

    def has_tests(self):
        """ Checks to see if there are actually tests associated with this object"""
        if self.test_type == self.FUNCTION:
            return not(self.input_values == '[]' )
        elif self.test_type == self.NUMSOL:
            return not(self.output_values == '[]' )
        else:
            return bool(json.loads(self.input_values) or json.loads(self.output_values))

    def set_function(self, s):
        """ set the testing suite for a function """
        if self.test_type == self.FUNCTION:
            self.input_values = s
        else:
            raise Exception('Tried to set a test for the wrong test type')

class CodeBlock(models.Model):
    """
    A code sample for use in html/css/js explorations

    .. note:: these will be used for all source-code in the future

    Attributes: 
        filename (CharField): the name of the 'file' for the source code (used in rendering html/css/js)
        filetype (CharField): Type of code, distinguished by standard extension: *py*, *html*, *css*, *js*

exploration/views.py
from django.shortcuts import render, get_object_or_404

from .models import Exploration, Slide

def index(request):
    exploration_list = Exploration.objects.all()
    return render(request, 'exploration/index.html', {'exploration_list': exploration_list})

def exploration(request, pk):
    exploration = get_object_or_404(Exploration, pk=pk)
    slides = exploration.slide_set.all()
    return render(request, 'exploration/exploration.html', {'exploration': exploration, 'slides': slides})

glossary/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404

from glossary.models import Word, Glossary

def index(request):
    word_list = Word.objects.order_by('word')
    context = {'glossary': {'title': 'Glossary'}, 'word_list': word_list}
    return render(request, 'glossary/global.html', context)

def glossary(request, unit_number):
    glossaries = get_list_or_404(Glossary, unit_number=unit_number)
    return render(request, 'glossary/glossary.html', {'glossary_list': glossaries, 'unit': glossaries[0].title })

def word(request, word_id):
    w = get_object_or_404(Word, id=word_id)
    return render(request, 'glossary/word_details.html', {'word': w})

quiz/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse

from quiz.models import Quiz, Question, Choice

def index(request):
    quiz_list = Quiz.objects.all()
    return render(request, 'quiz/index.html', {'quiz_list': quiz_list})

def quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    questions = quiz.all_questions()
    return render(request, 'quiz/quiz.html', {'quiz': quiz, 'question_list': questions})

courseware/templates/courseware/base.html
{% extends "base.html" %}
{% block title %}University of Waterloo OpenCS - {% block subtitle %}{% endblock subtitle%}{% endblock %}
{% block breadcrumb %}
{{ block.super }}
{% if course %}
    &gt;<a href="{% url "courseware:course" course.slug %}">{{ course.title }}</a>
    {% if unit %}
    &gt;<a href="{% url "courseware:unit" course.slug unit.position %}">{{ unit.position }}. {{ unit.title}}</a>
        {% if module %}
        &gt;<a href="">Step {{ module.position }}</a>
        {% endif %}
    {% endif %}
{% endif %}
{% endblock breadcrumb %}

courseware/templates/courseware/builtins.html
{% extends "courseware/base.html" %}

{% block breadcrumb %}
{{ block.super }}
&gt;<a href="{% url "courseware:builtins" course.slug %}">Built-ins</a>
{% endblock breadcrumb %}

{% block scripts %}
{{ block.super }}
<script src="/static/scripts/sorttable.js"></script>
{% endblock scripts %}


{% block content %}
<section id="main">
<h1>{{ collection.title }}</h1>    
<table class="sortable">
    <thead>
        <tr><th>ID</th><th>Name</th><th>Description</th>{% if "python" not in course.slug %}<th>Type</th>{% endif %}<th>Module</th><th>Step</th><th>Explanation</th><th>Example</th></tr>
    </thead>
    <tbody>{% for builtin in collection.builtins %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><code class="lang-{{ builtin.language }}">{{ builtin.name }}</code></td>
        <td>{{ builtin.description|safe }}</td>
        {% if "python" not in course.slug %}
        <td>{{ builtin.language }} {{ builtin.b_type }}</td>
        {% endif %}
        <td>{% if builtin.unit_number %}<a href="{% url 'courseware:unit' builtin.course.slug builtin.unit_number %}">{{ builtin.unit_number }}</a>{% endif %}</td>
        <td>{% if builtin.module_number %}<a href="{% url 'courseware:module' builtin.course.slug builtin.unit_number builtin.module_number %}">{{ builtin.module_number }}</a>{% endif %}</td>
        <td>{{ builtin.explanation|safe }}</td>
        <td>{{ builtin.example|safe }}</td>
    </tr>
    {% endfor %}</tbody>
</ul>
</section>
{% endblock content %}

courseware/templates/courseware/course_index.html
{% extends "courseware/base.html" %}

{% block subtitle %}{{ course.title }}{% endblock subtitle %}
{% block content %}
<section id="main">
    {% if unit_list %}
    <h1>Modules</h1>
    <div class="unit-selector">
        {% for unit in unit_list %}
        <a class="unit" href="{% url "courseware:unit" course.slug unit.position %}">
            <div class="unit-icon"><img src="{{ unit.image.url }}" /></div>
            <div class="unit-title">
                <h2>{{ unit.position }}. {{ unit.title }}</h2>
            </div>
            <div class="checkmark top-right"></div>
        </a>
        {% endfor %}
    </div>
    {% else %}
       <p>This course is coming soon.</p>
    {% endif %}
</section>
{% endblock content %}

{% block postscripts %}
<script src="/static/scripts/courseware/storage.js"></script>
<script>
var ids = [{%for unit in unit_list%}{{unit.id}},{% endfor %}];
var us = document.getElementsByClassName('unit')
var i;
for (i in ids) {
    storage.getUnitCompleted(ids[i], (function (complete) {
        console.log(this);
        console.log('setting completion status', complete);
        if (complete) {
            this.className += " completed";
        }
    }).bind(us[i]));
}
</script>
{% endblock postscripts %}

courseware/templates/courseware/exploration.html
{% extends "courseware/module_base.html" %}

{% block scripts%}
{{ block.super }}
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular-sanitize.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular-resource.js"></script>
<script src="/static/scripts/opencs-ace-build/src/ace.js"></script>
<script src="/static/scripts/ui-ace.js"></script>
<script src="/static/scripts/courseware/uw-slide-show.js"></script>
<script src="/static/scripts/python-socket.js"></script>
<script> var ps = new PythonSocket("{{python_socket}}");</script>
<script src="/static/scripts/courseware/panel-layout.js"></script>
<script src="/static/scripts/glossary/glossary-module.js"></script>
<script src="/static/scripts/courseware/exploration.js"></script>
<link rel="stylesheet" href="/static/css/glossary-module.css">
{% endblock scripts %}

{% block postscripts %}
{% endblock postscripts %}

{% block content %}
<div ng-app="explorationApp" ng-controller="exploreCtrl" ng-init="exploration={{serialized|escape }}; ">

{% if exploration.slide_set %}
<div uw-slide-show previous="{{ prev_module.position|default:"false" }}" next="{{ next_module.position|default:"false" }}">
<div class="slide-wrapper">
    <h1 style="margin:0">Instructions</h1>
    <div uw-exp-slide ng-repeat="s in exploration.slides" slide="s" check-last-slide>
    </div>
</div>
<div class="slide-wrapper">
    <div layout controls="false">
        {# for some reason, this new layout requires going back 4 ancestors#}
        <div pane class="code-input" ui-ace="aceOptions" ng-model="codeInput['py']"></div>
        <div pane class="rounded-box"><pre class="code-output" code-output aria-live="polite" aria-atomic="true"></pre></div>

    </div>
    <div class="buttons">
        <button ng-click="runCode()">Run</button>
        <button ng-click="stopCode()">Stop</button>
        <span class="checkmark" ng-show="success()"></span>
        <button style="position:absolute;right:2rem;" ng-click="restoreCode()">Restore</button>
    </div>
</div>
</div>
{% else %}
    <p>This exploration is mysteriously blank</p>
{% endif %}
</div>
{% endblock content %}

courseware/templates/courseware/glossary.html
{% extends "courseware/base.html" %}

{% block breadcrumb %}
{{ block.super }}
&gt;<a href="{% url "courseware:glossary" course.slug %}">Glossary</a>
{% endblock breadcrumb %}

{% block scripts %}
{{ block.super }}
<script src="/static/scripts/sorttable.js"></script>
{% endblock scripts %}


{% block content %}
<section id="main">
<h1>{{ glossary.title }}</h1>    
<table class="sortable">
    <thead>
        <tr><th>Term</th><th>Module</th><th>Step</th><th>Definition</th></tr>
    </thead>
    <tbody>{% for word in glossary.word_set.all %}
    <tr>
        <td><a href="{% url 'glossary:word_detail' word.id %}">{{ word.word }}</a></td>
        <td><a href="{% url 'courseware:unit' course.slug word.unit_number %}">{{ word.unit_number }}</a></td>
        <td><a href="{% url 'courseware:module' course.slug word.unit_number word.module_number %}">{{ word.module_number }}</a></td>
        <td>{{ word.definition }}</td>
    </tr>
    {% endfor %}</tbody>
</ul>
</section>
{% endblock content %}

courseware/templates/courseware/index.html
{% extends "courseware/base.html" %}

{% block subtitle %}Course Index{% endblock subtitle %}
{% block scripts %}
{{block.super}}
<link rel="stylesheet" href="/static/css/course.css">
{% endblock scripts %}

{% load staticfiles %}
{% block content %}
<section id="main">
    {% if course_list %}
    <h1>Courses</h1>
    <div class="course-selector">
        {% for course in course_list %}{% if not course.hidden %}
        <a class="course" href="{% url "courseware:course" course.slug %}">
            <div class="logo">{% if course.logo %}
            <img src="{{course.logo.url}}" alt="{{ course.title|default:"Open CS Courseware" }}"/>
            {% else %}
            <img src="{% static "images/course-opencs.png" %}" alt="{{ course.title|default:"Open CS Courseware"}}"/>
            {% endif %}</div>
            <div class="title">
                <h2>{{ course.title }}</h2>
                {{course.description|safe}}
            </div>
        </a>
        {% endif %}{% endfor %}
    </div>
    {% else %}
       <p>There are no courses available at the moment.</p>
    {% endif %}
</section>
{% endblock content %}

courseware/templates/courseware/module_base.html
{% extends "courseware/base.html" %}
{% block subtitle %}{{course.title}}{% endblock subtitle %}
{% block scripts %}
<script src="/static/scripts/courseware/storage.js"></script>
<script>
var courseSlug = '{{course.slug}}';
var unitId = {{unit.id}};
var unitPosition = {{unit.position}};
var modulePosition = {{module.position}};
var moduleId = {{module.id}};
</script>
{% endblock scripts %}

courseware/templates/courseware/quiz.html
{% extends "courseware/module_base.html" %}

{% block scripts%}
{{ block.super }}
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular-sanitize.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular-resource.js"></script>
<script src="/static/scripts/courseware/uw-slide-show.js"></script>
<script src="/static/scripts/glossary/glossary-module.js"></script>
<script src="/static/scripts/courseware/quiz.js"></script>
<link rel="stylesheet" href="/static/css/popups.css">
{% endblock scripts %}

{% block postscripts %}
{% endblock postscripts %}

{% block content %}
<div ng-app="quizApp" ng-init="quiz={{serialized|escape }}">

{% if quiz.question_set %}
<div uw-slide-show previous="{{ prev_module.position|default:"false" }}" next="{{ next_module.position|default:"false" }}">
<div uw-question ng-repeat="q in quiz.questions" question="q" check-last-slide>
</div>
</div>
{% else %}
    <p>This quiz is mysteriously blank</p>
{% endif %}
</div>
{% endblock content %}

courseware/templates/courseware/slideshow.html
{% extends "courseware/module_base.html" %}

{% block scripts%}
{{ block.super }}
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular-resource.js"></script>
<script src="/static/scripts/glossary/glossary-module.js"></script>
<script src="/static/scripts/courseware/uw-slide-show.js"></script>
<link rel="stylesheet" href="/static/css/popups.css">
{% endblock scripts %}

{% block postscripts %}
{% endblock postscripts %}

{% block content %}
<div ng-app="uwSlideShow" ng-init="slideshow={{serialized|escape }}">

<div uw-slide-show previous="{{ prev_module.position|default:"false" }}" next="{{ next_module.position|default:"false" }}">
    <div class="slide-wrapper">
        <div uw-slide="s" ng-repeat="s in slideshow.slides" check-last-slide>
        </div>
    </div>
</div>

</div>
{% endblock content %}

courseware/templates/courseware/unit_index.html
{% extends "courseware/base.html" %}

{% block subtitle %}{{ course.title }}{% endblock subtitle %}
{% block content %}
{% load static %}
<section id="main">
        <h1>{{ unit.title }}</h1>
        <div class="module-selector">
            {% for module in module_list %}
            <a class="module" href="{% url "courseware:module" course.slug unit.position module.position %}">
                <div class="checkmark top-right"></div>
                <h2>{{ module.title }}</h2>
                {% if module.icon %}<div class="module-icon"><img src="/static/images/{{ module.icon }}.png" /></div>
                {% else %}<div class="module-icon"><img src="/static/images/{{ module.content_type.model }}.png" /></div>
                {% endif %}
            </a>
            {% endfor %}
        </div>
</section>
{% endblock content %}
{% block postscripts %}
<script src="/static/scripts/courseware/storage.js"></script>
<script>
(function () {
var ids = [{%for module in module_list%}{{module.id}},{% endfor %}];
var ms = document.getElementsByClassName('module')
var i;
for (i in ms) {
    if (storage.getModuleCompleted(ids[i]))
        ms[i].className += " completed";
}

{% if next_unit.position %}
// Create a next unit button
nav = document.createElement('nav');
nav.setAttribute('class', 'top-right');
bn = document.createElement('button');
bn.innerHTML = 'Next module';
bn.setAttribute('class', 'unit next');
bn.onclick = function() {
    document.location.href = '../{{ next_unit.position }}';
}
nav.appendChild(bn);
window.addEventListener('load', function () { 
    m = document.getElementById('main')
    m.setAttribute('class', 'unit-index');
    m.appendChild(nav); 
});
{% endif %}
})();
</script>
{% endblock postscripts %}

courseware/templates/courseware/video_index.html
{% extends "courseware/base.html" %}

{% block subtitle %}{{ course.title }} - Videos{% endblock subtitle %}

{% block breadcrumb %}
{{ block.super }}
&gt;<a href="{% url "courseware:videos" course.slug %}">Videos</a>
{% endblock breadcrumb %}

{% block content %}
{% load static %}
<section id="main">
    <h1>{{course.title}} videos</h1>
    {% for unit in units %}
    <h2>{{ unit.position }}. {{unit.title}}</h2>
        <div class="module-selector">
            {% for module in unit.videos %}
            <a class="module video" href="{% url "courseware:module" module.unit.course.slug module.unit.position module.position %}">
                <div class="module-title"><h2>Part {{ module.position }}</h2></div>
                {% if module.icon %}<div class="module-icon"><img src="/static/images/{{ module.icon }}.png" /></div>
                {% else %}<div class="module-icon"><img src="/static/images/{{ module.content_type.model }}.png" /></div>
                {% endif %}
            </a>
            {% endfor %}
        </div>
    {% endfor %}
</section>
{% endblock content %}
{% block postscripts %}
<script src="/static/scripts/courseware/storage.js"></script>
<script>
var ids = [{%for module in module_list%}{{module.id}},{% endfor %}];
var ms = document.getElementsByClassName('module')
var i;
for (i in ms) {
    if (storage.getModuleCompleted(ids[i]))
        ms[i].className += " completed";
}
</script>
{% endblock postscripts %}